- name: install the nginx from a remote repo
  yum: name=epel-release state=present

- name: install nginx
  yum: name=nginx state=latest

- name: copy conf file
  template: src=default.conf.j2 dest=/etc/nginx/conf.d/default.conf

- name: start nginx
  service: name=nginx state=started

- name: enabled nginx
  service: name=nginx enabled=yes
