- name: configure django web server using gunicorn
  hosts: webservers
  sudo: yes
  gather_facts: no
  roles:
    - web

- name: configure proxy server using nginx
  hosts: proxyservers
  sudo: yes
  gather_facts: no
  roles:
    - proxy
